services:
    nuxt:
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 3000:3000
        env_file:
            - .env
        command: bun run dev --watch
        networks:
            - app-network
        hostname: nuxt

networks:
    app-network:
