services:
    postgres:
        image: postgres:13
        ports:
            - 5432:5432
        volumes:
            - ./postgres:/var/lib/postgresql/data
        environment:
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_DB=${DB_NAME}
        networks:
            - app-network
        hostname: postgres

networks:
    app-network:
